language: python
python:
  - "3.9.7"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python -m pip install flake8

script:
  - python manage.py test
  - black --check .
  - flake8 --exclude doghub_app/migrations

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "saANZpidsAQUP+iUfpsReykKDffIgXC1anjcqaCNu3PKKB6Fba6FIPWDOyfcy+523u/urK9Wt4D5vvJxDiLZ88d/arwhuhCkVRHtH/Jg0LYHd1mGnvlCgjM8SbAGr3j+wD7Jy47R29s7Sg31PS8TLsv39qB2Koh0/e7nKLXaGkGF99kawF3GHP/+zVfCfvuE9Er8V+Bd/1sIbSsyHW7QaxrpmzH99a6b8RAOz3ra7MPcn+PV+4BTmcn8rdftp/Uw1S4oJO0H3w/eqWIVsAh8kMw06BnEBsQ5OXBPIY+mr4Fy3xWa5qKih+pj2bu4lTKmByG5cvqIeeqO8ufTn4WKxCkouYjm6dszmINZYmxTjP1xfKgd/JOXil5nA2YB7EYhpJPECfbI+3v1AwkNfND3rtcgkqywbrjnwYBMBTkIXx8B+xw6Zs1s9Ix0OsZPIqtm7smsYoG7fNptfEFvl+O4QUfFi33WGK1HyrG8t5oPYB3lrlMohuqDSsSZMzX6jDuLz3Hncb58O/QxvT5P3mXf3N4lVWL08BoW2dInwZxnp2Wg8dwnYmpl4Xwh4BXs6vSg/yQO/GRuYWbaZ/DGlY06ijuKw7fgudJNFjXgb+LnDviZ0qpKIdCGGHVXHm9uliv1OUPVUSiEknSfFKAA8FshlBPuk+c4ARZXh6hmCZ+E738="
  secret_access_key:
    secure: "eVyLFznPSk8yZzuz4yYN/DWRzEiqvnjz6mAzWrh16Z/FDuSTvB0MVXTBdw5QwDxmm5OlvX9F+4JqKHF+OeZvEioUwv9x/XEQFRh/45rA/eg/XxjGIZg9hQahp6XRZTpqIycXOOK0OYlObSsww3a+EVhIBtLQeyTMtgSh07MadDQd6Aaf+1H5783WNBKBQBYV7+zgEiardJ3qHorLXtV4htk5Rb0z4wJjROZACLKCBm4kaUjru5Q+7qx71Ujvso0LdCzP3vZTHnz2t0qncaxfohMiSax6z8fXhQRJJk5bhODKvvAzvY6ZyK9mfgaxw0EWk4PIJXf4K79Z63HfDnFLrZotdV95VqL3GKwJYUNvuccdp4FIjjIfqVByVkIhbH7FEk6GILytlxaAuval+zYJQZ9ofceXTNOzifD68zYYnR3ZP8pnORAObrtZhXln/hmLN8l1xTvMyjpxRpLwyqqGE+xzMhDd1QXOA1n1nPhLvTxQcQxEXK+dO6PeLRhrIUNTivxnEIBPzbNSVyVgBiG5jr9qe2XxTX/jTSCBoa5b66ZZ6TuSmyiwcceqKy2P0PHh9kfVEyq3+nrdsn7ZdVChpk+WA/LHRQCtd79nvIt3Or0FhkTdzAbjb1QvubMzKxsd+uWCe694fXTro8do+PYZ0+5Yh9areF/7Nf5TiM5Nt1c="
  region: "us-west-2"
  app: "django-tutorial"
  env: "doghub-develop-env"
  bucket_name: "elasticbeanstalk-us-west-2-730437625654"
  on:
    repo: gcivil-nyu-org/INET-Monday-Spring2023-Team-1
    branch:
      - develop

after_deploy:
  - rm db.sqlite3
