language: python
python:
  - "3.9.7"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python -m pip install flake8

script:
  - python manage.py test
  - black --check .
  - flake8 --exclude doghub_app/migrations

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "hnfvHaJUfXdUOV0p++45wSpH4Nrlm++oxmGQbb5hYK18POdZtiNq0o490uANb4GFv/3y/mpngmeQQW6VC7hHTIuZyh09ffI0UYCXnFiPr4Tse9qcRIRhQ1X/SRKKZKEvvAiTdi9jgwmgBNSDqrLmnc+ilRojhgCrS5piR6KbK+fn81sNrDUMFch0RHBDavQn9LfTNFQXME+z4/haLllIKGq2z/AB4KQ2wq1vzRvS8H1VF2vgk+DYPDU1h8YLzMBwHUp6zTR+hBtcP4UeewPGwarP8fZwMTTW7psfZCnbBrx1S4MF+Y/tc3XGYxQGHpQZv2oJ6xiV+QcJcGoJ9n8KuYq3iNmXe0WEhjBVWWuFbkhm9rdAMahErg5n/XRjLMUxkvyabmL11p/yLjFyXZwyScMEXK3nhUZrkJPT30W7XyZPZH6Ly6qYMHGbz9VYKPPt8efEm3V7NGgEVBKdVlRe0YXwb2paBZqpTC2T2S1RiGTGehEJAV5hzHfS7rl5L0JoE05nPGAcjffc5HLIOpz7nV3V4A9n/jfAAF/PxFy/wSPwQ1NnpZBzcLn2Kz/KeIBLLkTIBlJ/lEzHWtMv6531XNI+ZfC0zHXcz/uUDT0U2lSv5VzGKPCunxQ6RIvKjppMnwehllt1rEdY1M24gfxle9lwjF5HVnpFh2VXGUIBVIM="
  secret_access_key:
    secure: "DW4eP/+YAJyxzEnmX+vZuE0icrmb7Qb4+JYdIHpyzAWMME1cVaRQEf/lsbSjTYu3NMWCeKeKlwEgSJMkfWpv8lo050Cu0fssA53vyDZMjcT9JWN9efb0rl6NgAwo4M8eolB8DqKdkckzwyovYGt1JDm2vBSSvUnhvOiy5IkvFCMZzjsDqzo9xm87Qx5KXJh0nrm4evZUX/IC/K3FF17mrrM5K+SH1TVwhlpBFm8H7Lt95aEk8TAufQucroeC1xvziM5vGlJVAr5OW8rzFn677iAlB+7cKxNUYFUh779JCtNY4AFAqOVSxxHbNH29dLSmKPzGNe6AiCmw1XeWVVzqS3CYVlcQPBVpyiDIbBbf80Dj/aYxqi+9xWJ2d5hy2dvMKf/7iOo8Xadx9iZ+JpSr3kSkGi/k1wcOyj7ryy9/MJ3e+irqRrtIiF3VvUJExsDKdbYqVqHV7eef2naH6TcmnUxQAB40vxy4uRQlTSr2xCBpdn1x7IZTZTA9CGGcECK14FXWdKMSZNPSXbo3btIcvnJD0Hcu7/cP56b0OikuJuL6XwAmCz1KH+0wr6wZJKXMaob8BGpE53RQCSdczIgJF0fbgagZZW5oaOBVGuWmXxSpLB/ky3/bGmdG096Ly/88eAgbw+RwiIxAZwKroqZu2XmDRVR4nIP9u6QB9WcAMzI="
  region: "us-west-2"
  app: "django-tutorial"
  env: "doghub-develop-env"
  bucket_name: "elasticbeanstalk-us-west-2-730437625654"
  on:
    repo: gcivil-nyu-org/INET-Monday-Spring2023-Team-1
    branch:
      - develop
