language: python
python:
  - "3.9.7"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python -m pip install flake8

script:
  - python manage.py test
  - black --check .
  - flake8 --exclude doghub_app/migrations

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "hnfvHaJUfXdUOV0p++45wSpH4Nrlm++oxmGQbb5hYK18POdZtiNq0o490uANb4GFv/3y/mpngmeQQW6VC7hHTIuZyh09ffI0UYCXnFiPr4Tse9qcRIRhQ1X/SRKKZKEvvAiTdi9jgwmgBNSDqrLmnc+ilRojhgCrS5piR6KbK+fn81sNrDUMFch0RHBDavQn9LfTNFQXME+z4/haLllIKGq2z/AB4KQ2wq1vzRvS8H1VF2vgk+DYPDU1h8YLzMBwHUp6zTR+hBtcP4UeewPGwarP8fZwMTTW7psfZCnbBrx1S4MF+Y/tc3XGYxQGHpQZv2oJ6xiV+QcJcGoJ9n8KuYq3iNmXe0WEhjBVWWuFbkhm9rdAMahErg5n/XRjLMUxkvyabmL11p/yLjFyXZwyScMEXK3nhUZrkJPT30W7XyZPZH6Ly6qYMHGbz9VYKPPt8efEm3V7NGgEVBKdVlRe0YXwb2paBZqpTC2T2S1RiGTGehEJAV5hzHfS7rl5L0JoE05nPGAcjffc5HLIOpz7nV3V4A9n/jfAAF/PxFy/wSPwQ1NnpZBzcLn2Kz/KeIBLLkTIBlJ/lEzHWtMv6531XNI+ZfC0zHXcz/uUDT0U2lSv5VzGKPCunxQ6RIvKjppMnwehllt1rEdY1M24gfxle9lwjF5HVnpFh2VXGUIBVIM="
  secret_access_key:
    secure: "BBqpf2z9LBG91KebAjVdCIQcn/X6wFE/GqQQ8UvZO5pgkpNKW+KHIEMvDBTyCJZQJFGsPP7n31WG65o7cldEfPxiQffEHa6WJpuyuuBdhsiqtXd0U9JlyNq+blq5fXXi8afL9UkKjlMNTzlNK+2FbmOTZOiEYVX6iR6y7BmdUrwNugr71dibtbFXqnudaXOGi7KsAWTHoO3Vd2/RSqZntkPRXlQgL9CiALn1MayOhDNYekp8MsjLDrMkTWPh61w9oHl2aAE8netSVmgH4UhpMkkRNvxUE07YTDc47hDoiBU2IVkWA5pj/PvkinnHsExBTpHWrksH/J94aHh6HBeASzKOAQ7lasIBD8qEwXiwun8Mv14XgE7cFKN76TN1drf3dFa5Sazsuskar5TMK0FOZpqy81xUrtzKGcPsnWzdXAvlvrCDyAvAI+YQziyrctlVYpNp/OByWEWwy+s05B73uwxg274MhAPOOd+PbIN+RLXu6QdcLRSYMnmvWp/TER3jVPeThF+DPV8C642S6Iyrvax9KMy9zuBKMER7DpI5GO9Z/UhH/EWm+wZ+Yg83fdIiZUi/f+vyc69jrHfuHjuG1zjXKEC/sDpVl3+QUn/AAYaoZPf37a4Ru+I/8BUuOL3h+FMTajZCrMebCwl4iDGOjj9xvmdwYBvMI5JpVSNuAkA="
  region: "us-west-2"
  app: "django-tutorial"
  env: "doghub-develop-env"
  bucket_name: "elasticbeanstalk-us-west-2-730437625654"
  on:
    repo: gcivil-nyu-org/INET-Monday-Spring2023-Team-1
    branch:
      - develop

after_deploy:
  - rm db.sqlite3
