language: python
python:
  - "3.9.7"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python -m pip install flake8

script:
  - python manage.py test
  - black --check .
  - flake8 --exclude doghub_app/migrations

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "UKXq5FK1FgCJEN6zrKRX6pzqNiaeiW4AnFfwqZyHfT0cYg895VcVM6zc3Sf5YRq6zOPoagJ4Y2osgoei0mtoTit9q3umWDgaOd7Ja4pe5PSxNV/aCS7Ly/WLe4WwuAskYJgU8lNSfIpxEcdP5BZs1S7rmy2RnE//m/6W0vhMLL5Tw0Aa3HRrBWo8HzshILM5Uaqlgiq+Si28tTWkkTMwrahmXsQ3cR5a4eqJ1ScYLMvmUfr3oWDFbWAJsqFP9tOvUySoWD99tBuPuCIxeZ+/7foTSHDz/1+2ARnGx28Fcj23sIuwWpZXPQ9yUQdn+V0ABCFL7siahrBMJ1OWzbm7LzCR+8u8BgU6kCz6v5BZsLNCdObh7KGhgNqpFRdwJnZ1whQOsjgH3YgeIMAlMhlX9MNSotpjJEZMj9dUNiz9O0qTI2vfVsbcV04HydP9z0RWI+WJtVawBgKzsFk75ytFSUCMS919pD7i7dodltJyo3DS4FoxyU2CNXwoR4UXf5cPnXWr/ix20ltWrdC/DVazuFPudmQu42C6qjshV2xTJQRYIu5vUfbPiX3pkanM3GysVuOc/9k1KhSQtOvqeeg4LGfhPbtngZwzNjpjLmX3j8JD25z+3b2e5rEbozwzunH0XFe/RG/Rrz3BbqSde9ZPxoUk/cGeK7ZjmTZ6VYWOSu4="
  secret_access_key:
    secure: "eVyLFznPSk8yZzuz4yYN/DWRzEiqvnjz6mAzWrh16Z/FDuSTvB0MVXTBdw5QwDxmm5OlvX9F+4JqKHF+OeZvEioUwv9x/XEQFRh/45rA/eg/XxjGIZg9hQahp6XRZTpqIycXOOK0OYlObSsww3a+EVhIBtLQeyTMtgSh07MadDQd6Aaf+1H5783WNBKBQBYV7+zgEiardJ3qHorLXtV4htk5Rb0z4wJjROZACLKCBm4kaUjru5Q+7qx71Ujvso0LdCzP3vZTHnz2t0qncaxfohMiSax6z8fXhQRJJk5bhODKvvAzvY6ZyK9mfgaxw0EWk4PIJXf4K79Z63HfDnFLrZotdV95VqL3GKwJYUNvuccdp4FIjjIfqVByVkIhbH7FEk6GILytlxaAuval+zYJQZ9ofceXTNOzifD68zYYnR3ZP8pnORAObrtZhXln/hmLN8l1xTvMyjpxRpLwyqqGE+xzMhDd1QXOA1n1nPhLvTxQcQxEXK+dO6PeLRhrIUNTivxnEIBPzbNSVyVgBiG5jr9qe2XxTX/jTSCBoa5b66ZZ6TuSmyiwcceqKy2P0PHh9kfVEyq3+nrdsn7ZdVChpk+WA/LHRQCtd79nvIt3Or0FhkTdzAbjb1QvubMzKxsd+uWCe694fXTro8do+PYZ0+5Yh9areF/7Nf5TiM5Nt1c="
  region: "us-west-2"
  app: "django-tutorial"
  env: "doghub-develop-env"
  bucket_name: "elasticbeanstalk-us-west-2-730437625654"
  on:
    repo: gcivil-nyu-org/INET-Monday-Spring2023-Team-1
    branch:
      - develop
